<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirm Your Registration</title>
</head>
<body>

<h1 style="color: green">Registration confirmation</h1>
<h2>Hello, ${name}!</h2>
<p>To confirm your registration, please click on the following link:</p>
<a href="${confirmationLink}">Confirm</a>
<p>Thank you for choosing our service!</p>

</body>

</html>